### ISSUE TITLE
Create sale.order.line for sales.order

### ISSUE THREAD

**Issue by lozo2010** [patricoos/PortaCapena.OdooJsonRpcClient#17]
Hi.

I try to create a sale order with multiple lines. 
Currently, I am creating the order and then when I get the id, I create the lines for this orderId.

Is it possible to create the order with the lines at the same time?

If this cannot be done, multiple lines can be created at the same time without calling the repository.CreateAsync (modelItem); for each line?

```

                var repositoryProduct = new OdooRepository<ProductModel>(odooConfig);
                var repository = new OdooRepository<SaleOrderModel>(odooConfig);
                var model = OdooDictionaryModel.Create(() => new SaleOrderModel()
                 {
                    PartnerId = 32,
                    State = StatusSaleOrderOdooEnum.SalesOrder,
                 });
                 var result = await repository.CreateAsync(model);
                if (result.Succeed && result.Value > 0)
                {
                    foreach (var item in items)
                    {
                        var product = await repositoryProduct.Query()
                          .Where(x => x.Name, OdooOperator.EqualsTo, items.Name)
                          .FirstOrDefaultAsync();
                        var modelItem = OdooDictionaryModel.Create(() => new SaleOrderLineModel()
                        {
                            OrderId = result.Value,
                            ProductId = product.Value.Id,
                            ProductUomQty = 20

                        });
                        var result1 = await repository.CreateAsync(modelItem);

                    }
                }
```

**Comment by patricoos** [comment]
Hey,
I do it in the same way. As I remember U can do it also like that:

`
 var purchaseOrder = OdooDictionaryModel.Create(() => new PurchaseOrderOdooModel
            {
                DateOrder = DateTime.Now,
                PartnerId = 9,
                CurrencyId = 15,
                CompanyId = 1,
                Name = "test purchase",
            });

            var lines = new[] { 
                OdooDictionaryModel.Create(() => new PurchaseOrderLineOdooModel()
                {
                    Name = "test purchase line",
                })
            };
            purchaseOrder.Add(x => x.OrderLine, lines);

            var createResult = await odooClient.CreateAsync(purchaseOrder);
`
I don't have time now to test it, but as I remember I have some problems with that approach.

**Comment by lozo2010** [comment]
I have this error with this code

![image](https://user-images.githubusercontent.com/9165283/121496020-5cafa300-c9da-11eb-90ef-d6992635cbbe.png)
```

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/controllers/rpc.py", line 77, in jsonrpc
    return dispatch_rpc(service, method, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 139, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 41, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 174, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 181, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 165, in execute_cr
    result = odoo.api.call_kw(recs, method, args, kw)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 385, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 365, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-185>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 314, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale_stock/models/sale_order.py", line 67, in create
    return super(SaleOrder, self).create(vals)
  File "<decorator-gen-178>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 314, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/models/sale.py", line 463, in create
    result = super(SaleOrder, self).create(vals)
  File "<decorator-gen-109>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 269, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3810, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3970, in _create
    for other, data in zip(others, data_list)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2897, in create
    self.write_batch(record_values, True)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2923, in write_batch
    return self.write_real(records_commands_list, create)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3093, in write_real
    unlink(comodel.search(domain))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1648, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4497, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: can't adapt type 'dict'
```




```

var repositoryProduct = new OdooRepository<ProductModel>(odooConfig);
                var repositoryOrder = new OdooRepository<SaleOrderModel>(odooConfig);
                var itemOrder = new List<SaleOrderLineModel>();
                foreach (var item in order.Items)
                {
                    var product = await repositoryProduct.Query()
                      .Where(x => x.Name, OdooOperator.EqualsTo, item.ProductId)
                      .FirstOrDefaultAsync();


                    if (product.Succeed && product.Value != null)
                    {
                        itemOrder.Add(new SaleOrderLineModel()
                        {
                            OrderId = 0,
                            ProductId = product.Value.Id,
                            ProductUomQty = Convert.ToDouble(item.ProductAmount)

                        });
                    }
                    else
                    {
                        return new ErrorResponseModel() { Success = 0, ErrorMessage = ProductNotFound };
                    }
                }
                var model = OdooDictionaryModel.Create(() => new SaleOrderModel()
                 {
                    PartnerId = 32,
                    State = StatusSaleOrderOdooEnum.SalesOrder,
                 });
                foreach (var item in itemOrder)
                {
                    var lines = new[] {
                        OdooDictionaryModel.Create(() => new SaleOrderLineModel()
                        {
                            ProductId = item.ProductId,
                            ProductUomQty = Convert.ToDouble(item.ProductUomQty)

                        })
                    };
                    model.Add(x => x.OrderLine, lines);

                }
                var result = await repositoryOrder.CreateAsync(model);

```

**Comment by zhhangtaao** [comment]
I also encountered the same problem, how did you solve this problem?

**Comment by bvillers-jr** [comment]
Odoo doesn't seem to take a dictionary, therefore the error: can't adapt type 'dict'

The solution for me was to simply convert the dictionary to an array. 

            var lines = new[] {
                        OdooDictionaryModel.Create(() => new SaleOrderLineOdooModel()
                        {
                            ProductId = long.Parse(ProductID),
                            ProductUomQty = 1

                        })**_.ToArray()_** };

**Comment by bvillers-jr** [comment]
I'm not sure why this is marked closed. The issue remains. Odoo is capable of accepting an order with the order lines in one XMLRPC. I think there is some issue with the fact that we're passing it in as a dict. Odoo doesn't want a dict. for this. I tried converting the object to an array. I get a transaction succeeded message from Odoo, but the order line isn't present in the UI.


            var line = new[] {
                        OdooDictionaryModel.Create(() => new SaleOrderLineOdooModel()
                        {
                            ProductId = long.Parse(ProductID),
                            ProductUomQty = 1

                        }).ToArray() };


            somodel.Add(x => x.OrderLine, line);

**Comment by JeanPhilippeLux** [comment]
Hi, here is my first test for adding lines with an order : 

 var sorepository = new OdooRepository<SaleOrderOdooModel>(TestConfig);
 var somodel = OdooDictionaryModel.Create(() => new SaleOrderOdooModel()
 {
     PartnerId = 1,
     //CreateDate = DateTime.Now,
     Note = "Automatically created as the result of a license transfer",
     State = StatusOdooEnum.SalesOrder
 });


 var line =
         OdooDictionaryModel.Create(() => new SaleOrderLineOdooDto()
         {
             ProductId = 6,
             ProductUomQty = 1,
             PriceUnit = 1,
             CustomerLead = 1,
             Name = "test"

         });

 List<object> test = new()
 {
     new object[] { 0, 0, line.GetRecord() }.ToArray()
 };

 somodel.Add(x => x.OrderLine, test);


 var soresult = await sorepository.CreateAsync(somodel);


I have to make a cleaner code, but if that can help.
