### ISSUE TITLE
Error query all productos

### ISSUE THREAD

**Issue by lozo2010** [patricoos/PortaCapena.OdooJsonRpcClient#23]
Hi.

I have this error when get all product.

`Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at PortaCapena.OdooJsonRpcClient.OdooClient.CallAndDeserializeAsync[T](OdooRequestModel request)`

This is the code. 
Is it possible not to deserialize the response?
````
var repository = new OdooRepository<ProductModel>(odooConfig);
var products = await repository.Query().ToListAsync();
````

**Comment by patricoos** [comment]
Try get model and save it one more time

**Comment by lozo2010** [comment]
Same error. It must be for the number of records or with a specific record. if I make the call with .Take (200) it works correctly

**Comment by patricoos** [comment]
No. Problem is somewhere else. You have a corrupt record in the database nad odoo can not download it. Try to increase take count to find this one and delete it.

**Comment by lozo2010** [comment]
This is the error. 

I have requested that they increase the timeout of nigix


![image](https://user-images.githubusercontent.com/9165283/128301339-9cb40f17-88e9-4d8c-bf70-4ea90b9a849f.png)

**Comment by patricoos** [comment]
How many products do you have in db?

**Comment by lozo2010** [comment]
Around 47,000 products. We have increased the timeout. 

Calling jsonrpc directly, using only the fields I need, it responds in few seconds.
![image](https://user-images.githubusercontent.com/9165283/129745537-579e6355-15d6-46a6-9ec2-a5624c620ca8.png)

I have tried to create a model with only the fields and it still does not work

**Comment by lozo2010** [comment]
Ok, I have added SelectSimplifiedModel() in the call with the simplified model and now I only get the data I need and it does not skip the timeout
Thanks for the support.
