### ISSUE TITLE
Get Users API is not working

### ISSUE THREAD

**Issue by MrXeNoNNN** [patricoos/PortaCapena.OdooJsonRpcClient#34]
Hello! 
A few months ago, I created a small for management Odoo, that informs us about the status of the users, etc. I'm creating a request to get the list of users but is throwing an exception that the object is not deserialized correctly
`Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: f. Path 'result', line 1, position 47.
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at PortaCapena.OdooJsonRpcClient.OdooClient.CallAndDeserializeAsync[T](OdooRequestModel request)`
1 month ago was working perfectly, I think that Odoo changed the response. Can you update the package? Thank you!

**Comment by patricoos** [comment]
Hello, Thanks for your message. I will try to solve this issue as soon as possible. I understand that you are using the latest version of odoo?

**Comment by MrXeNoNNN** [comment]
Yes, version 1.0.18

**Comment by patricoos** [comment]
Have you tried to generate a new user model?

**Comment by MrXeNoNNN** [comment]
I found the issue, the problem was that password was changed, but I think that you need to improve Exceptions, I checked directly in your tests, the problem was in methods LoginAsync, and the result does not succeed, you might throw an Exception about with more details. Thank you!
![image](https://user-images.githubusercontent.com/94171115/155520556-224bf4f0-b6e9-4ec3-ae18-4f6ef59a9d40.png)

**Comment by MrXeNoNNN** [comment]
Also, you can add some additional models for table "res.users"., include them in the next release. Thank you!

**Comment by patricoos** [comment]
I don't add any models to the library. There are model changes in each version of odoo. The library works generically and you should generate the models yourself
