### ISSUE TITLE
Odoo 17 Projects - Bug cannot unmarshal properties_definition

### ISSUE THREAD

**Issue by gosysdata** [patricoos/PortaCapena.OdooJsonRpcClient#90]
System.Exception
  HResult=0x80131500
  Message=Cannot unmarshal Enum 'OdooValueTypeEnum' - 'properties_definition'
  Source=PortaCapena.OdooJsonRpcClient
  StackTrace:
   at PortaCapena.OdooJsonRpcClient.Models.OdooPropertyInfo.ToOdooValueTypeEnum(String value)
   at PortaCapena.OdooJsonRpcClient.Models.OdooPropertyInfo.get_PropertyValueType()
   at PortaCapena.OdooJsonRpcClient.Converters.OdooModelMapper.ConvertToDotNetPropertyTypeName(KeyValuePair`2 property, String tableName)
   at PortaCapena.OdooJsonRpcClient.Converters.OdooModelMapper.GetDotNetModel(String tableName, Dictionary`2 properties, Boolean addSummary)
   at Program.<<Main>$>d__0.MoveNext() in

**Comment by gosysdata** [comment]
While executing

var tableName = "project.project";
var modelResult = await odooClient.GetModelAsync(tableName);

**Comment by patricoos** [comment]
odoo version?

**Comment by gosysdata** [comment]
17.0 enterprise on odoo.sh

On 8 Jan 2024, at 23:23, Patrick ***@***.***> wrote:

﻿

odoo version?

**Comment by alberthoekstra** [comment]
I got the same error.
This is the version info:
```json
{
  "server_version": "saas~17.1+e",
  "server_version_info": [
    "saas~17",
    1,
    0,
    "final",
    0,
    "e"
  ],
  "server_serie": "saas~17.1",
  "protocol_version": 1
}

```

**Comment by WMLondo** [comment]
Same error
